# Starter pipeline

trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'vs2017-win2016'
  group: 'Katalon Studio'
  
stages:
- stage: Execute Automation Test ${{ variables.targetEnvironment }}
  displayName: Execute Automation Stage
  jobs:
  - job: Execute
    displayName: Execute Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: katalonTask@0
      displayName: 'Execute Katalon Studio project'
      inputs:
        version: '7.7.0'
        executeArgs: '-apiKey="$(apiKey)" -browserType="Chrome" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/All Test Cases"'