# Starter pipeline

trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'vs2017-win2016'
  group: 'KatalonStudio'
  targetEnvironment: 'UAT'

  
stages:
- stage: "Execute_Automation_Test_${{ variables.targetEnvironment }}"
  displayName: Execute Automation Stage
  jobs:
  - job: Execute
    displayName: Execute Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: echo $(apiKey)
    - task: katalonTask@0
      displayName: 'Execute Katalon Studio project'
      inputs:
        version: '7.7.0'
        executeArgs: '-apiKey="$(apiKey)" -browserType="Chrome" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/All Test Cases"'