# Starter pipeline

trigger:
- master

resources:
- repo: self

parameters:
- name: browserType
  displayName: Select Browser Type To Execute Test
  type: string
  default: Chrome
  values:
  - Chrome
  - Web Service

variables:
  - name: vmImageName
    value: 'vs2017-win2016'
  - group: KatalonStudio
  - name: targetEnvironment
    value : 'UAT'

  
stages:
- stage: "Execute_Automation_Test_${{ variables.targetEnvironment }}"
  displayName: Execute Automation Stage
  jobs:
  - job: Execute
    displayName: Execute Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: echo $(katalonApiKey)
    - script: echo $(vmImageName)
    - task: katalonTask@0
      displayName: 'Execute Katalon Studio project'
      inputs:
        version: '7.7.0'
        executeArgs: '-apiKey="$(katalonApiKey)" -browserType="${{ parameters.browserType }}" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/All Test Cases"'