# Starter pipeline

trigger:
- master

resources:
- repo: self

parameters:
- name: imageName
  displayName: Select Agent Machine Type To Execute Test
  type: string
  default: windows-latest
  values:
  - vs2017-win2016
  - windows-latest

- name: browserType
  displayName: Select Browser Type To Execute Test
  type: string
  default: Chrome
  values:
  - Chrome
  - Web Service

- name: executionSuiteName
  displayName: Input Your Test Suite To Execute
  type: string
  default: All Test Cases

- name: retryNumber
  displayName: Input Your Retry Number To Re-Run Test Suites
  type: number
  default: 2

- name: katalonVersion
  displayName: Input Your Katalon Version
  type: string
  default: 7.7.0

variables:
  ## Create variable group in "Library" to hold secret variables
  - group: KatalonStudio
  ## Can map the target environment with the branch name
  - name: targetEnvironment
    value : 'UAT'

  
stages:
- stage: "Set_up_environment_before_run_katalon_tests"
  displayName: Set Up Environmnet Stage
  jobs:
  - job: Clone_Database
    displayName: Clone Database
    pool:
      vmImage: ${{ parameters.imageName }}
    steps:
    - script: echo $(katalonApiKey)
    - script: echo ${{ parameters.imageName }}
- stage: "Execute_Automation_Test_${{ variables.targetEnvironment }}"
  displayName: Execute Automation Stage
  jobs:
  - job: Execute
    displayName: Execute Test
    pool:
      vmImage: ${{ parameters.imageName }}
    steps:
    - script: cd
    - task: katalonTask@0
      displayName: 'Execute Katalon Studio project'
      inputs:
        version: '${{ parameters.katalonVersion}}'
        executeArgs: '-summaryReport -reportFolder="./testReport" -apiKey="$(katalonApiKey)" -browserType="${{ parameters.browserType }}" -retry=${{ parameters.retryNumber }} -statusDelay=15 -testSuitePath="Test Suites/${{ parameters.executionSuiteName }}"'
    
- stage: "Clean_up_environment_before_run_katalon_tests"
  displayName: Clean Up Environmnet Stage
  jobs:
  - job: Notify_test_result_to_slack
    displayName: Notify Test Result
    pool:
      vmImage: ${{ parameters.imageName }}
    steps:
    - script: echo $(katalonApiKey)
    - script: echo ${{ parameters.imageName }}
  - job: Clean_up_environmnet
    displayName: Clean up environment
    pool:
      vmImage: ${{ parameters.imageName }}
    steps:
    - script: echo $(katalonApiKey)
    - script: echo ${{ parameters.imageName }}